package com.ui.resource;

public class R {
	public static final String image_url_icon = "/res/logo.png";
	public static final String image_url_small_icon = "/res/logo_small.png";
	public static final String image_url_head = "res/head.png";
	public static final String image_url_friend_normal = "res/tab_friend_normal.png";
	public static final String image_url_friend_pressed = "res/tab_friend_pressed.png";
	public static final String image_url_dialog_normal = "res/tab_dialog_normal.png";
	public static final String image_url_dialog_pressed = "res/tab_dialog_pressed.png";
	public static final String image_url_space_normal = "res/tab_space_normal.png";
	public static final String image_url_space_pressed = "res/tab_space_pressed.png";
	public static final String image_url_setting_normal = "res/setting_normal.png";
	public static final String image_url_add_normal = "res/add_friend_normal.png";
	public static final String image_url_min_normal = "res/window_min_normal.png";
	public static final String image_url_max_normal = "res/window_max_normal.png";
	public static final String image_url_exit_normal = "res/window_exit_normal.png";
	public static final String image_url_popup_exit_normal = "res/popup_exit_normal.png";
	public static final String image_url_popup_exit_pressed = "/res/popup_exit_pressed.png";
	public static final String image_url_popup_min_normal = "res/popup_min_normal.png";
	public static final String image_url_popup_min_pressed = "/res/popup_min_pressed.png";
	public static final String image_url_heart = "res/small_heart.png";
	public static final String image_url_font_normal = "res/font_normal.png";
	public static final String image_url_font_pressed = "res/font_pressed.png";
	public static final String image_url_emoticon_normal = "res/emoticon_normal.png";
	public static final String image_url_emoticon_pressed = "res/emoticon_pressed.png";
	public static final String image_url_file_normal = "res/file_normal.png";
	public static final String image_url_file_pressed = "res/file_pressed.png";
	public static final String image_url_screenshot_normal = "res/screenshot_normal.png";
	public static final String image_url_screenshot_pressed = "res/screenshot_pressed.png";
	public static final String image_url_videochat_normal = "res/videochat_normal.png";
	public static final String image_url_videochat_pressed = "res/videochat_pressed.png";
	public static final String image__popup_warn = "res/popup_warn.png";
	public static final String image_slider_dot_normal = "res/slider_dot_normal.png";
	public static final String image_slider_dot_pressed = "res/slider_dot_pressed.png";
	public static final String image_myinfo_normal = "res/myinfo_normal.png";
	public static final String image_myinfo_pressed = "res/myinfo_pressed.png";
	public static final String image_small_team_logo = "res/small_team_logo.png";
	public static final String image_lv_bg = "res/lv_bg.png";
}
